#!/usr/bin/env node
/**
 * Copies the authored art in `game_assets/` into `public/assets/` so Next can serve it.
 *
 * `game_assets/` stays the source of truth in version control (that is where the user drops
 * new art); `public/assets/` is generated and gitignored. Runs automatically before `dev`
 * and `build`, and on demand via `npm run assets:sync`.
 *
 * Phase 0 scope: a faithful copy plus a manifest of what landed. The typed art-override
 * manifest and responsive background variants arrive with the asset pipeline proper
 * (docs/tech/asset-pipeline.md §3–4).
 */

import { cp, mkdir, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = join(root, 'game_assets');
const targetRoot = join(root, 'public', 'assets');

/** source (relative to game_assets) → target (relative to public/assets) */
const MAPPINGS = [
  ['UI/Backgrounds', 'backgrounds'],
  ['UI/Classes', 'classes'],
  ['UI/Kenney_FantasyUIAssets', 'ui/kenney-fantasy'],
  ['VFX/Kenney_VFXParticles', 'vfx/kenney-particles'],
];

async function countFiles(dir) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? await countFiles(join(dir, entry.name)) : 1;
  }
  return total;
}

async function main() {
  if (!existsSync(sourceRoot)) {
    console.warn(`[assets] no game_assets/ directory at ${sourceRoot} — nothing to sync.`);
    return;
  }

  await mkdir(targetRoot, { recursive: true });
  const summary = [];

  for (const [from, to] of MAPPINGS) {
    const source = join(sourceRoot, from);
    const target = join(targetRoot, to);

    if (!existsSync(source)) {
      console.warn(`[assets] skipping missing source: ${relative(root, source)}`);
      continue;
    }

    await cp(source, target, { recursive: true, force: true });
    const files = await countFiles(target);
    summary.push({ source: from, served: `/assets/${to}`, files });
  }

  // The optional player-supplied soundtrack lives here (USER_QUESTIONS Q13).
  const audioDir = join(targetRoot, 'audio');
  await mkdir(audioDir, { recursive: true });
  await writeFile(
    join(audioDir, 'README.txt'),
    [
      'Optional background music.',
      '',
      'Drop an MP3 named exactly `bgm.mp3` into this folder and the game will loop it as',
      'background music, with its own toggle and volume slider in Settings. Remove the file',
      'and the game is silent again — no code changes either way.',
      '',
      'This folder is generated by scripts/sync-assets.mjs; bgm.mp3 itself is gitignored.',
      '',
    ].join('\n'),
    'utf8',
  );

  const manifest = {
    generatedBy: 'scripts/sync-assets.mjs',
    note: 'Generated file — edit game_assets/ instead. See docs/tech/asset-pipeline.md.',
    groups: summary,
  };
  await writeFile(
    join(targetRoot, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf8',
  );

  const total = summary.reduce((sum, group) => sum + group.files, 0);
  console.log(`[assets] synced ${total} files into public/assets/`);
  for (const group of summary) {
    console.log(`[assets]   ${group.served.padEnd(26)} ${String(group.files).padStart(4)} files`);
  }
}

main().catch((error) => {
  console.error('[assets] sync failed:', error);
  process.exitCode = 1;
});
