/**
 * Turn the vendored game-icons.net SVGs into the module the app imports.
 *
 *   npm run icons:sync
 *
 * Reads `scripts/icon-map.mjs` (the decisions) and `game_assets/icons/**` (the artwork, tracked
 * exactly as backgrounds and portraits are) and writes `src/components/icons/vendored.ts`.
 *
 * Three things it does that matter:
 *
 * - **Strips the preview backing.** Upstream files are `<path d="M0 0h512v512H0z"/>` — a black
 *   square — followed by a white foreground. Shipping the square paints a filled block behind
 *   every glyph. It also drops the hard-coded `fill="#fff"`, so the artwork inherits `currentColor`
 *   the way the hand-drawn family did and every existing colour class keeps working.
 * - **Does not touch the coordinates.** Rounding them looked like free money — one unit at 512
 *   scale is 0.03px at render size, and it halved the payload. It also silently destroyed the
 *   artwork, because SVG path data is *compact*: in `M10.5.75l3.25.5` the token `10.5.75` is two
 *   numbers, `10.5` and `.75`. A `\d+\.\d+` regex matches the first, rounds it to `11`, and leaves
 *   `.75` glued on — two coordinates become one and the shape collapses into a sliver. Every gate
 *   passed; a screenshot found it. If the payload ever needs cutting, the tool is a real path
 *   parser (svgo), never a regex.
 * - **Carries the author through.** game-icons.net is CC BY 3.0 **per icon**, so the author is not
 *   metadata here, it is the licence. It comes from the vendored directory name and lands in both
 *   the generated module and the CREDITS.md table.
 *
 * Generated output is committed: the build must not depend on this script having been run, and a
 * diff on the generated file is a useful review signal when a mapping changes.
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ICON_SOURCES } from './icon-map.mjs';

const ROOT = join(import.meta.dirname, '..');
const VENDOR = join(ROOT, 'game_assets', 'icons');
const OUT = join(ROOT, 'src', 'components', 'icons', 'vendored.ts');

/** The preview backing, in the forms upstream writes it. */
const BACKING = /<path[^>]*\sd="M0 0h512v512H0z"[^>]*\/>/g;
const WHITE = /\sfill="(?:#fff|#FFF|#ffffff|white)"/g;

function index() {
  const found = new Map();
  for (const author of readdirSync(VENDOR)) {
    const dir = join(VENDOR, author);
    if (!statSync(dir).isDirectory()) continue;
    for (const file of readdirSync(dir)) {
      if (file.endsWith('.svg')) found.set(file.replace(/\.svg$/, ''), author);
    }
  }
  return found;
}

function extract(name, author) {
  const raw = readFileSync(join(VENDOR, author, `${name}.svg`), 'utf8');
  const body = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(BACKING, '')
    .replace(WHITE, '')
    .trim();

  if (body.includes('M0 0h512v512H0z')) throw new Error(`${name}: preview backing survived`);

  /*
   * Every one of the 67 reduces to a single path, so the generated module carries the `d` string
   * alone rather than markup. That keeps the renderer a plain `<path d={…} />` — no
   * `dangerouslySetInnerHTML`, no HTML parsing at runtime, and a type error rather than a blank
   * square if the shape ever changes. A future icon with two paths trips this deliberately.
   */
  const paths = [...body.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*\/?>/g)].map((m) => m[1]);
  if (paths.length !== 1) {
    throw new Error(
      `${name}: expected exactly one path, found ${paths.length} — see the note in extract()`,
    );
  }
  return paths[0];
}

function main() {
  const available = index();
  const rows = [];
  const missing = [];

  for (const [id, name] of Object.entries(ICON_SOURCES)) {
    if (name === null) continue;
    const author = available.get(name);
    if (!author) {
      missing.push(`${id} → ${name}`);
      continue;
    }
    rows.push({ id, name, author, d: extract(name, author) });
  }

  if (missing.length) {
    console.error(`Not vendored under game_assets/icons/:\n  ${missing.join('\n  ')}`);
    process.exit(1);
  }

  const bytes = rows.reduce((sum, r) => sum + r.d.length, 0);
  const authors = [...new Set(rows.map((r) => r.author))].sort();

  const file = `/*
 * GENERATED by \`npm run icons:sync\` — do not edit.
 *
 * Source: game-icons.net artwork vendored under \`game_assets/icons/<author>/<name>.svg\`,
 * chosen in \`scripts/icon-map.mjs\`. Licence: CC BY 3.0, per icon, per author — see CREDITS.md.
 *
 * ${rows.length} icons · ${authors.length} authors · ${(bytes / 1024).toFixed(1)} KB of path data.
 */

/** One vendored drawing: its upstream name, its author (the licence), and its 512-space path. */
export interface VendoredIcon {
  readonly name: string;
  readonly author: string;
  readonly d: string;
}

/** The 512×512 grid every game-icons drawing is authored on. */
export const VENDORED_VIEWBOX = '0 0 512 512';

export const VENDORED_ICONS = {
${rows
  .map(
    (r) =>
      `  ${r.id}: {\n    name: '${r.name}',\n    author: '${r.author}',\n    d: ${JSON.stringify(r.d)},\n  },`,
  )
  .join('\n')}
} as const satisfies Record<string, VendoredIcon>;

export type VendoredIconId = keyof typeof VENDORED_ICONS;

/** Distinct authors whose work ships, for the CREDITS.md census. */
export const VENDORED_AUTHORS = [${authors.map((a) => `'${a}'`).join(', ')}] as const;
`;

  writeFileSync(OUT, file);
  console.log(
    `[icons] ${rows.length} icons · ${authors.length} authors (${authors.join(', ')}) · ` +
      `${(bytes / 1024).toFixed(1)} KB of path data → src/components/icons/vendored.ts`,
  );
}

main();
